### ISSUE TITLE
Better warnings if not login

### ISSUE THREAD

**Issue by chinesedfan** [yacheng/jsplayground#1]
No sure whether here is the right place to give a feedback of https://jsplayground.taobao.org.

If not login and click `编译并运行`, it shows `未登录用户暂无创建权限`. I think it is better to say `暂无运行权限`.

**Comment by yacheng** [comment]
Thank you for your issue. We will take your advice and repair it in the near future. You can use this place in the future  https://github.com/taobaofed/jsplayground/issues  :)
